(require 'hayabusa)
(require 'ert)
(require 'ert-x)

(ert-deftest test-hayabusa-replace-char ()
  (with-temp-buffer
    (let* ((hayabusa-keys-alist '((?j . ?-)))
	   (last-command-event ?j)
	   (current-prefix-arg nil))
      (ert-simulate-command (list #'hayabusa-insert))
      (ert-simulate-command (list #'hayabusa-insert))
      (ert-simulate-command (list #'hayabusa-insert))
      (ert-simulate-command (list #'ignore))
      (ert-simulate-command (list #'hayabusa-insert))
      (should (string= "-jj" (buffer-string)))
      )))

(ert-deftest test-hayabusa-insert-alt-char ()
  (with-temp-buffer
    (let* ((hayabusa-keys-alist '((?j . ?-)))
	   (last-command-event ?j))
      (let* ((current-prefix-arg '-))
	(ert-simulate-command (list #'hayabusa-insert))
	(ert-simulate-command (list #'hayabusa-insert)))    
      (let* ((current-prefix-arg '-1))
	(ert-simulate-command (list #'hayabusa-insert))
	(ert-simulate-command (list #'hayabusa-insert)))
      (should (string= "----" (buffer-string))))))

(ert-deftest test-hayabusa-self-insert ()
  (with-temp-buffer
    (let* ((hayabusa-keys-alist '((?j . ?-)))
	   (last-command-event ?j))
      (let* ((current-prefix-arg 0))
	(ert-simulate-command (list #'hayabusa-insert))
	(should (string= "" (buffer-string))))
      (let* ((current-prefix-arg 1))
	(ert-simulate-command (list #'hayabusa-insert))
	(should (string= "j" (buffer-string)))
	(ert-simulate-command (list #'hayabusa-insert))
	(should (string= "jj" (buffer-string)))))))

(ert-deftest test-hayabusa-single-insert ()
  (with-temp-buffer
    (let* ((hayabusa-keys-alist '((?j . ?-)))
	   (last-command-event ?j))
      (let* ((current-prefix-arg '(4)))
	(ert-simulate-command (list #'hayabusa-insert)))
      (should (string= "j" (buffer-string)))
      (let* ((current-prefix-arg '(16)))
	(ert-simulate-command (list #'hayabusa-insert)))
      (should (string= "j-" (buffer-string)))
      (let* ((current-prefix-arg '(64)))
	(ert-simulate-command (list #'hayabusa-insert)))
      (should (string= "j-j" (buffer-string))))))
;;;
;;;(ert-deftest test-hayabusa-insert-in-isearch ()
;;;  (with-temp-buffer
;;;    (let* ((hayabusa-keys-alist '((?j . ?-))))
;;;      (call-interactively #'isearch-forward)
;;;      (setq isearch-string "")
;;;      (ert-simulate-command (list #'hayabusa-insert nil ?j))
;;;      (should (string= "j" isearch-string))
;;;      (ert-simulate-command (list #'hayabusa-insert nil ?j))
;;;      (should (string= "-" isearch-string)))))


